# Generated by Django 5.0.3 on 2024-03-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper_agency", "0003_alter_newspaper_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspaper",
            name="content",
            field=models.TextField(),
        ),
    ]
