# Generated by Django 5.0.3 on 2024-03-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper_agency', '0004_alter_newspaper_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='newspaper_agency.newspaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Commentaries',
                'ordering': ('-created_time',),
            },
        ),
    ]
