# Generated by Django 5.0.3 on 2024-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper_agency", "0005_commentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
