# Generated by Django 4.1 on 2024-03-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper_agency", "0006_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
