# Generated by Django 4.1 on 2024-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper_agency", "0007_alter_commentary_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
